export interface KnownSite {
  domain: string;
  testUrl: string;
}

export const KNOWN_RECIPE_SITES: KnownSite[] = [
  { domain: 'allrecipes.com', testUrl: 'https://www.allrecipes.com/recipe/213742/meatball-nirvana/' },
  { domain: 'foodnetwork.com', testUrl: 'https://www.foodnetwork.com/recipes/ina-garten/perfect-roast-chicken-recipe-1940592' },
  { domain: 'epicurious.com', testUrl: 'https://www.epicurious.com/recipes/food/views/classic-chocolate-chip-cookies' },
  { domain: 'bonappetit.com', testUrl: 'https://www.bonappetit.com/recipe/bas-best-chocolate-chip-cookies' },
  { domain: 'food52.com', testUrl: 'https://food52.com/recipes/82275-the-best-chocolate-chip-cookies' },
  { domain: 'seriouseats.com', testUrl: 'https://www.seriouseats.com/the-best-chocolate-chip-cookies-recipe' },
  { domain: 'cooking.nytimes.com', testUrl: 'https://cooking.nytimes.com/recipes/1018684-chocolate-chip-cookies' },
  { domain: 'tasty.co', testUrl: 'https://tasty.co/recipe/the-best-chewy-chocolate-chip-cookies' },
  { domain: 'delish.com', testUrl: 'https://www.delish.com/cooking/recipe-ideas/a20088581/best-chocolate-chip-cookies-recipe/' },
  { domain: 'simplyrecipes.com', testUrl: 'https://www.simplyrecipes.com/recipes/chocolate_chip_cookies/' },
  { domain: 'thekitchn.com', testUrl: 'https://www.thekitchn.com/how-to-make-the-best-chocolate-chip-cookies-cooking-lessons-from-the-kitchn-58056' },
  { domain: 'smittenkitchen.com', testUrl: 'https://smittenkitchen.com/2008/07/consummate-chocolate-chip-cookies/' },
  { domain: 'halfbakedharvest.com', testUrl: 'https://www.halfbakedharvest.com/brown-butter-chocolate-chip-cookies/' },
  { domain: 'minimalistbaker.com', testUrl: 'https://minimalistbaker.com/vegan-chocolate-chip-cookies/' },
  { domain: 'cookingclassy.com', testUrl: 'https://www.cookingclassy.com/chocolate-chip-cookies/' },
  { domain: 'sallysbakingaddiction.com', testUrl: 'https://sallysbakingaddiction.com/chocolate-chip-cookies/' },
  { domain: 'budgetbytes.com', testUrl: 'https://www.budgetbytes.com/homemade-chocolate-chip-cookies/' },
  { domain: 'ohsheglows.com', testUrl: 'https://ohsheglows.com/2016/10/17/my-favourite-vegan-chocolate-chip-cookies/' },
  { domain: 'pinchofyum.com', testUrl: 'https://pinchofyum.com/the-best-soft-chocolate-chip-cookies' },
  { domain: 'skinnytaste.com', testUrl: 'https://www.skinnytaste.com/chocolate-chip-cookies/' },
  { domain: 'bbcgoodfood.com', testUrl: 'https://www.bbcgoodfood.com/recipes/ultimate-chocolate-chip-cookies' },
  { domain: 'jamieoliver.com', testUrl: 'https://www.jamieoliver.com/recipes/chocolate-recipes/jamies-easy-chocolate-cookies/' },
  { domain: 'taste.com.au', testUrl: 'https://www.taste.com.au/recipes/classic-choc-chip-cookies/f83e7b4f-5a94-4a69-9b76-0eea9a39ba25' },
  { domain: 'marmiton.org', testUrl: 'https://www.marmiton.org/recettes/recette_cookies-aux-pepites-de-chocolat_13892.aspx' },
  { domain: 'chefkoch.de', testUrl: 'https://www.chefkoch.de/rezepte/1061031209951433/Chocolate-Chip-Cookies.html' },
  { domain: 'giallozafferano.it', testUrl: 'https://ricette.giallozafferano.it/Biscotti-cookies-al-cioccolato.html' },
  { domain: 'recetasgratis.net', testUrl: 'https://www.recetasgratis.net/receta-de-galletas-con-chispas-de-chocolate-56788.html' },
  { domain: 'williams-sonoma.com', testUrl: 'https://www.williams-sonoma.com/recipe/classic-chocolate-chip-cookies.html' },
  { domain: 'marthastewart.com', testUrl: 'https://www.marthastewart.com/338185/soft-and-chewy-chocolate-chip-cookies' },
  { domain: 'eatingwell.com', testUrl: 'https://www.eatingwell.com/recipe/251015/healthier-chocolate-chip-cookies/' },
  { domain: 'cookinglight.com', testUrl: 'https://www.cookinglight.com/recipes/chocolate-chip-cookies' },
  { domain: 'wholefoodsmarket.com', testUrl: 'https://www.wholefoodsmarket.com/recipes/classic-chocolate-chip-cookies' },
  { domain: 'bettycrocker.com', testUrl: 'https://www.bettycrocker.com/recipes/ultimate-chocolate-chip-cookies/77c14e03-d8b0-4844-846d-f19304f61c57' },
  { domain: 'kingarthurbaking.com', testUrl: 'https://www.kingarthurbaking.com/recipes/chocolate-chip-cookies-recipe' },
  { domain: 'tasteofhome.com', testUrl: 'https://www.tasteofhome.com/recipes/chewy-chocolate-chip-cookies/' },
  { domain: 'cooksillustrated.com', testUrl: 'https://www.cooksillustrated.com/recipes/1313-perfect-chocolate-chip-cookies' },
  { domain: 'ambitiouskitchen.com', testUrl: 'https://www.ambitiouskitchen.com/the-best-chewy-chocolate-chip-cookies/' },
  { domain: 'loveandlemons.com', testUrl: 'https://www.loveandlemons.com/chocolate-chip-cookies/' },
  { domain: 'cookieandkate.com', testUrl: 'https://cookieandkate.com/classic-chocolate-chip-cookies-recipe/' },
  { domain: 'damndelicious.net', testUrl: 'https://damndelicious.net/2018/12/17/brown-butter-chocolate-chip-cookies/' },
  { domain: 'spendwithpennies.com', testUrl: 'https://www.spendwithpennies.com/best-chocolate-chip-cookies/' },
  { domain: 'thepioneerwoman.com', testUrl: 'https://www.thepioneerwoman.com/food-cooking/recipes/a32202986/chocolate-chip-cookies-recipe/' },
  { domain: 'yummly.com', testUrl: 'https://www.yummly.com/recipe/Chocolate-chip-cookies-9080583' },
  { domain: 'myrecipes.com', testUrl: 'https://www.myrecipes.com/recipe/classic-chocolate-chip-cookies' },
  { domain: 'bakerbynature.com', testUrl: 'https://bakerbynature.com/best-ever-chocolate-chip-cookies/' },
  { domain: 'onceuponachef.com', testUrl: 'https://www.onceuponachef.com/recipes/chocolate-chip-cookies.html' },
  { domain: 'thepioneerwoman.com', testUrl: 'https://www.thepioneerwoman.com/food-cooking/recipes/a11822/classic-chocolate-chip-cookies/' },
  { domain: 'barefootcontessa.com', testUrl: 'https://barefootcontessa.com/recipes/overnight-mac-and-cheese' },
  { domain: 'thespruceeats.com', testUrl: 'https://www.thespruceeats.com/classic-chocolate-chip-cookies-recipe-520375' },
  { domain: 'thewoksoflife.com', testUrl: 'https://thewoksoflife.com/chocolate-chip-cookies/' },
  { domain: 'gimmesomeoven.com', testUrl: 'https://www.gimmesomeoven.com/best-chocolate-chip-cookies-recipe/' },
  { domain: 'twopeasandtheirpod.com', testUrl: 'https://www.twopeasandtheirpod.com/the-best-chocolate-chip-cookies/' },
  { domain: 'browneyedbaker.com', testUrl: 'https://www.browneyedbaker.com/chocolate-chip-cookies/' },
  { domain: 'theurbanpoacher.com', testUrl: 'https://theurbanpoacher.com/recipes/chocolate-chip-cookies' },
  { domain: 'bakingmischief.com', testUrl: 'https://bakingmischief.com/best-chocolate-chip-cookies-recipe/' },
  { domain: 'averiecooks.com', testUrl: 'https://www.averiecooks.com/best-chocolate-chip-cookies/' },
  { domain: 'dinneratthezoo.com', testUrl: 'https://www.dinneratthezoo.com/chocolate-chip-cookie-recipe/' },
  { domain: 'iambaker.net', testUrl: 'https://iambaker.net/best-chocolate-chip-cookies/' },
  { domain: 'crazyforcrust.com', testUrl: 'https://www.crazyforcrust.com/best-chocolate-chip-cookies/' },
  { domain: 'jocooks.com', testUrl: 'https://www.jocooks.com/recipes/chocolate-chip-cookies/' },
  { domain: 'natashaskitchen.com', testUrl: 'https://natashaskitchen.com/chocolate-chip-cookies-recipe/' },
];
